# -*- coding: utf-8 -*-
"""Road Accident Prevention System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18S9s0qJCTYv9Q7JUf7cL1h3smkUJVC_H
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import time
from collections import Counter
from imblearn.over_sampling import SMOTE
import matplotlib.ticker as ticker
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,MinMaxScaler, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import RepeatedStratifiedKFold, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import KFold


import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline

import zipfile

with zipfile.ZipFile('/content/archive(6).zip', 'r') as z:
    with z.open('Road Accident Data.csv') as f:
        data = pd.read_csv(f)

print(data.head())

data.head()

data.sample(5)

data.shape

data.columns

data.describe(include='all')

data.dtypes



cols_to_fix = ['Carriageway_Hazards',
'Road_Surface_Conditions'] # 'Special_Conditions_at_Site' does not exist in the dataframe data.info() output

for col in cols_to_fix:
    data[col] = data[col].fillna('None')

print(data[cols_to_fix].isnull().sum())

# convert to datatime
data['Accident Date']=pd.to_datetime(data['Accident Date'])

# Extracting
